/**
 * Copyright (c) 2007-2013, AVIQ Bulgaria Ltd
 *
 * Project:     AVIQTV
 * Filename:    Param.java
 * Author:      alek
 * Date:        16 Jul 2013
 * Description: Enumerate application parameter names
 */

package com.aviq.tv.android.home.utils;

public class Param
{
	public static enum User
	{
		/**
		 * Ethernet MAC address
		 */
		MAC,

		/**
		 * The selected language
		 */
		LANGUAGE,

		/**
		 * ABMP Base URL
		 */
		ABMP_URL,

		/**
		 * Brand name to represent the box on ABMP
		 */
		BRAND,

		/**
		 * Boolean set to true if first time boot
		 */
		IS_FIRST_TIME,

		/**
		 * Boolean set to true to indicate the system is running after software update
		 */
		IS_AFTER_UPDATE,

		/**
		 * Last played channel
		 */
		CURRENT_CHANNEL,

		/**
		 * The full path to the last downloaded firmware
		 */
		UPGRADE_FILE,

		/**
		 * The version of the last downloaded firmware
		 */
		UPGRADE_VERSION,

		/**
		 * The brand of the last downloaded firmware
		 */
		UPGRADE_BRAND,

		/**
		 * Registered RayV user account name
		 */
		RAYV_USER,

		/**
		 * Registered RayV account password
		 */
		RAYV_PASS
	}

	public static enum System
	{
		/**
		 * Number of seconds for pinging the register service on ABMP
		 */
		ABMP_REGISTER_INTERVAL,

		/**
		 * Set to true if the release please a role of a stub version
		 * In this case the software attempt to upgrade only, if no new version
		 * loads StubLoungeActivity instead of LoungeActivity
		 */
		IS_STUB,

		/**
		 * Timeout in seconds for the Alert dialogs to auto select default answer
		 */
		ALERT_TIMEOUT,

		/**
		 * Timeout in seconds for notification messages to be displayed
		 */
		DISPLAY_MESSAGE_TIMEOUT,

		/**
		 * EPG update interval in seconds
		 */
		EPG_UPDATE_INTERVAL,

		/**
		 * Number of days in the past for the EPG storage
		 */
		EPG_DAYS_PAST,

		/**
		 * Number of days ahead for the EPG storage
		 */
		EPG_DAYS_AHEAD,

		/**
		 * The name of the EPG provider, e.g. rayv, wilmaa, generic
		 */
		EPG_PROVIDER,

		/**
		 * The main url to the EPG server
		 */
		EPG_SERVER,

		/**
		 * The EPG service version
		 */
		EPG_VERSION,

		/**
		 * EPG channels url format
		 */
		EPG_CHANNELS_URL,

		/**
		 * EPG channel logo url format
		 */
		EPG_CHANNEL_LOGO_URL,

		/**
		 * Timeout in seconds for OSD to stay on screen
		 */
		OSD_CHANNELS_TIMEOUT,

		/**
		 * Timeout in seconds for VolumeBar OSD to stay on screen
		 */
		OSD_VOLUME_BAR_TIMEOUT,

		/**
		 * Number of seconds for ping if internet connection is available
		 */
		INTERNET_CHECK_INTERVAL,

		/**
		 * Timezone, like Europe/Zurich
		 */
		TIMEZONE,

		/**
		 * Enable/Disable proxy
		 */
		IS_PROXY_ENABLE,

		/**
		 * Proxy type (see Proxy.Type)
		 */
		PROXY_TYPE,

		/**
		 * Proxy host
		 */
		PROXY_HOST,

		/**
		 * Proxy port
		 */
		PROXY_PORT,

		/**
		 * timeout in seconds for connecting a socket to http server
		 */
		HTTP_CONNECT_TIMEOUT,

		/**
		 * timeout in seconds to read from http socket
		 */
		HTTP_READ_TIMEOUT,

		/**
		 * False is video playback must be turned off (debugging purpose only)
		 */
		IS_PLAY_VIDEO,

		/**
		 * False is mp3 playback (error sound) must be turned off (debugging purpose only)
		 */
		IS_PLAY_SOUND,

		/**
		 * Username for the WebDAV server where ACRA error reports are stored.
		 */
		ACRA_WEBDAV_USERNAME,

		/**
		 * Password for the WebDAV server where ACRA error reports are
		 * stored.
		 */
		ACRA_WEBDAV_PASSWORD,

		/**
		 * URL on the WebDAV server where ACRA error reports are stored.
		 */
		ACRA_WEBDAV_URL,

		/**
		 * File name template of the error report generated by ACRA.
		 */
		ACRA_WEBDAV_REPORT_TEMPLATE,

		/**
		 * Set to true/false whether the mode is Development or not.
		 */
		IS_DEVEL,

		/**
		 * Number of seconds to check for new firmware upgrade
		 */
		UPGRADE_CHECK_INTERVAL,

		/**
		 * Put the box in standby after some inactivity
		 */
		AUTO_STANDBY_INTERVAL,

		/**
		 * Log level: see standard Android levels for the Log class.
		 */
		LOG_LEVEL,

		/**
		 * How many times the player shall retry playing a channel before reporting an error.
		 * Note that this is 0-based, i.e. a value of 1 means two attempts.
		 */
		PLAYER_MAX_RETRY_ATTEMPS,

		/**
		 * Pattern composing channel stream url for RayV CDN provider
		 */
		RAYV_STREAM_URL_PATTERN,

	}
}
